# Generated by Django 2.2.3 on 2019-08-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule_engine_conditions',
            name='date_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
