# Generated by Django 2.2.3 on 2019-09-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_auto_20190903_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adgroupperformancereportmodel',
            old_name='adgroupid',
            new_name='AdGroupId',
        ),
    ]
