# Generated by Django 2.2.3 on 2019-09-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_adscheduler'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdScheduler',
            new_name='AdScheduler_Model',
        ),
    ]
