# Generated by Django 2.2.6 on 2019-10-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_auto_20190912_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdgroupPerformanceReportModel',
        ),
        migrations.DeleteModel(
            name='AdScheduler_Model',
        ),
        migrations.RemoveField(
            model_name='adwordscampaigngroup',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='adwordscampaignkeywords',
            name='group',
        ),
        migrations.RemoveField(
            model_name='adwordscampaignruleengine_adgroups',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='adwordscampaignruleengine_keywords',
            name='group',
        ),
        migrations.DeleteModel(
            name='CampaignPerformanceReportModel',
        ),
        migrations.DeleteModel(
            name='KeywordPerformanceReportModel',
        ),
        migrations.RemoveField(
            model_name='rule_engine_action',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='rule_engine_conditions',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='rule_engine_conditions',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='rule_engine_rules',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='AdwordsCampaign',
        ),
        migrations.DeleteModel(
            name='AdwordsCampaignGroup',
        ),
        migrations.DeleteModel(
            name='AdwordsCampaignKeywords',
        ),
        migrations.DeleteModel(
            name='AdwordsCampaignRuleEngine_adgroups',
        ),
        migrations.DeleteModel(
            name='AdwordsCampaignRuleEngine_keywords',
        ),
        migrations.DeleteModel(
            name='Rule_Engine_Action',
        ),
        migrations.DeleteModel(
            name='Rule_Engine_Conditions',
        ),
        migrations.DeleteModel(
            name='Rule_Engine_Recipe',
        ),
        migrations.DeleteModel(
            name='Rule_Engine_Rules',
        ),
    ]
